# Generated by Django 3.0.8 on 2021-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name=models.ImageField(default='image.jpg', upload_to='media'))),
                ('photo_title', models.CharField(max_length=200)),
                ('sender_username', models.CharField(max_length=200)),
                ('recipient_username', models.CharField(max_length=200)),
                ('sent_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='verifykey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=200)),
                ('stegokey', models.CharField(max_length=200)),
                ('stegokey_id', models.IntegerField(default=0)),
            ],
        ),
    ]
